import { Toaster } from '@modules/shared/components/atoms/toaster'
import { RainbowKitWrapper, ThemeWrapper } from '@organisms'

import './globals.css'

export const metadata = {
	title: 'Airdrop Hunter',
	description: 'Generated by create next app',
}

interface RootLayoutProps {
	children: React.ReactNode
}

export default function RootLayout({ children }: RootLayoutProps) {
	return (
		<html lang="en">
			<body>
				<main>
					<RainbowKitWrapper>
						<ThemeWrapper>{children}</ThemeWrapper>
					</RainbowKitWrapper>
					<Toaster />
				</main>
			</body>
		</html>
	)
}
